### ISSUE TITLE
Is it safe to use xor for the inner additions in (E)NH ?

### ISSUE THREAD

**Issue by pkhuong** [backtrace-labs/umash#15]
The codegen would be slightly neater for full-sized blocks if we could xor the message with our key in AVX256-sized blocks.

**Comment by lemire** [comment]
In my experience, you can easily mix carryless mult. with XOR, but it gets harder to interleave regular multiplications and additions.

(This does not answer your question, of course.)

**Comment by pkhuong** [comment]
Seems unlikely. `(m ^ k) - k` is xor-linear in `k` (http://www.goubin.fr/papers/arith-final.pdf), i.e., very predictable.

The core of the collision bound is `kc = (m' ^ k) c' + y`, or, equivalently, `kc = (m' + k - f_m'(k))c' + y`, where `f_m'(k) = (m' + k) - (m' ^ k)`, 

The condition becomes `k(c - c') + f_m'(k)c' = y`, where all but `k` (including `f_m'`) is attacker-controlled. It's not hard to imagine that `f_m'` might be affine wrt modular arithmetic for some `m'`. The expression becomes `k(c - c') - (dk + e)c' = k(c - c' + d) + ec' = y`, and at that point, an attacker simply has to make sure `c' = c - d`.
