### ISSUE TITLE
Incorrect comparison to hardware failure probability

### ISSUE THREAD

**Issue by tczajka** [backtrace-labs/umash#18]
Documentation states:
> However, we don't actually need double the entropy: in practice, anything stronger than $\approx 2^{-70}$ is dominated by hardware failure, incinerated datacenters, or war.

This is not true: if you fingerprint about 2^{35} items with that collision probability, you will start getting collisions. That is not very many items, certainly below hardware failure or warfare rates.

**Comment by pkhuong** [comment]
You're right that the birthday bound works like that, and I was being aggressive in that statement. I will definitely rephrase in the upcoming documentation re-edit.

Nevertheless, if the alternative were pairwise comparisons, the probability of hardware error (e.g., facebook reports 0.03% of machines suffer from at least one UNCOR each month https://users.ece.cmu.edu/~omutlu/pub/memory-errors-at-facebook_dsn15.pdf) during any of these many 2^69 comparisons is easily on par with the probability of collisions.
