### ISSUE TITLE
Maybe improve the xor-shift mult mixer to xor-shift add

### ISSUE THREAD

**Issue by rurban** [backtrace-labs/umash#3]
umash uses a well-established murmur-style xor-shift plus mult mixer. thanksfully mixing the seed in the middle.
but mult is rather slow. pengyhash uses a simplier xor-shift add mixer, with similar properties, just much faster, and easier to parallelize internally in the CPU.
```
                uint64_t b, s = ...;
		s[1] = (s[0] += (s[1] += b[1]) + b[0]) ^ (s[1] << 14 | s[1] >> 50);
		s[3] = (s[2] += (s[3] += b[3]) + b[2]) ^ (s[3] << 23 | s[3] >> 41);
		s[3] = (s[0] += (s[3] += b[3]) + b[0]) ^ (s[3] << 16 | s[3] >> 48);
		s[1] = (s[2] += (s[1] += b[1]) + b[2]) ^ (s[1] << 40 | s[1] >> 24);
```
Instead 3 dependent rounds of xor mult on words, do 2 rounds (1 and 3 are independent) of xor add on bytes. Would be worth to try I think.

**Comment by pkhuong** [comment]
We're not changing the output format anymore.
