### ISSUE TITLE
Minor typo in blog post

### ISSUE THREAD

**Issue by eddelbuettel** [backtrace-labs/umash#7]
Just came across [your Aug 24 post](https://engineering.backtrace.io/2020-08-24-umash-fast-enough-almost-universal-fingerprinting/) and it would appear it lacks a verb in the opening sentence:

> We accidentally a whole hash function… but we had a good reason! 

Maybe add "wrote" or "invented" ?

**Comment by pkhuong** [comment]
It's a meme. I considered fixing it, but it doesn't seem to hinder comprehension.

**Comment by eddelbuettel** [comment]
Hah, my bad. If it is a meme, got a URL for other uses?

**Comment by eddelbuettel** [comment]
Crikey. Never mind.  A quick Google search on "We accidentally a whole" leads to it, include to the Urban Dictionary.  

My bad.  Learn something new every day.
